### PR TITLE
fix: update cross-spawn version to 7.0.5 in package-lock.json

### PR DESCRIPTION
**Pull request by camelmasa**
The version in package.json has been updated, but the version in the lockfile has not been updated.

If you cannot update the version from 7.0.5, you will probably need to upgrade to 7.0.6.

### CODE REVIEW

**Comment by satazor** [comment]
Thanks for the PR. Need to fix the release process to deal with this. I will release a new patch afterwards.

**Comment by satazor** [comment]
Fixed. v7.0.6 released

**Comment by camelmasa** [comment]
Thanks for merge!

**Comment by mbtools** [comment]
Just in general, thank you for picking up the project again 👍

**Review by 22Noggin — COMMENTED** [review]
Absolutely love this one and would love to have access all the time !!!! Did an amazing job

**Pull request merged**
