### PR TITLE
ci: use npm install

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by DanielRuf** [comment]
So only node >= 6 is supported.

**Comment by satazor** [comment]
Node 6 is reaching EOL in April. In May, I will remove both node 4 and 6 support in a single release.

I will take care of this on that release.

**Comment by DanielRuf** [comment]
This PR is about using npm i vs npm ci.
It is not about Node.js 4 / 6.

**Comment by satazor** [comment]
@DanielRuf it’s related because each node version comes preinstalled with a specific npm version. I would like to keep using `npm ci` for versions that support it so that the package-lock is verified.

**Pull request closed without merging**
