### PR TITLE
Inline dependencies path-key and shebang-command

### PR DESCRIPTION
**Pull request by bibo5088**
Inlined three dependencies in total, (`path-key`, `shebang-command`, and `shebang-regex`)
[The regex](https://github.com/sindresorhus/shebang-regex/blob/master/index.js#L2) of `shebang-regex` being only 9 byte but coming with a package.json, typescript definition and LICENSE file for a total of 2 828 byte (**314 times bigger !**)

Also fixed eslint config which gave this error
`Error: Cannot find module 'eslint-config-moxy/addons/object-spread'`
and ran
`eslint . --fix`

### CODE REVIEW

**Comment by ehmicky** [comment]
I don't think inlining libraries is a good idea. This means `node-cross-spawn` would not get any updates from those three packages anymore, unless manually copied/pasted each time. TypeScript types would also be lost.

Also running `eslint --fix` should be a separate PR.

**Comment by bibo5088** [comment]
I agree with eslint fix needing to be a separate PR.

`path-key` is just a function returning the value of the `PATH` environement variable.
`shebang-command` parses a shebang.

Both of these libraries have no reason to change, so many things depend on shebang and `PATH` so operating systems will not change them, the backward compatibily is too important, plus why would they change them? `PATH` and shebang are fine as it is.

It would be like TC39 removing `console.log()`, it will never happen because it has no reason to be removed and it's used everywhere.

Typescript types are almost useless if you're not using typescript, if types are really important for you I would recommand converting the project to typescript.

I like typescript and use it for all my projects but it's up to the maintainers to decide if they want it or not.

**Comment by ehmicky** [comment]
> Both of these libraries have no reason to change

You never know.

Also the bundle size is only true if users aren't installing those dependencies (including through another dependency). Shared dependencies take fewer bytes than duplicated inlined ones.

**Comment by satazor** [comment]
The eslint error was fixed in master.

In regards to the inlining of deps: if you weight the advantages of inlining vs not inlining, we loose a lot of advantages to just one advantage, which is the file size. But as @ehmicky said, if you are installing these dependencies either directly or through others, there's no duplication, while inlining does duplicate. While not the case, this is especially important for frontend code where you want your source code to be as small as possible.

**Comment by jimmywarting** [comment]
If you don't inline them, and want to continue getting updates from all of this dependencies (that are now esm-only variants) then you also need to switch to ESM-only variant

Some of the big impacters are:

Sindre that is updating all his 1000+ packages
babel 8 is going to become ESM only
node-fetch@3 is esm only

**Pull request closed without merging**
