### PR TITLE
Fix certain arguments not being correctly escaped or causing batch syntax error

### LINKED ISSUE #82: Bad escaping when an argument has quotes followed by a pipe
`"foo|bar>baz"`

### PR DESCRIPTION
**Pull request by satazor**
More specifically:
- Fix a bug that made it impossible to escape an argument that contained quotes followed by `>` or other special chars, e.g.: `"foo|bar"`, fixes #82
- Fix a bug were a command containing `%x%` would be replaced with the contents of the `x` environment variable, fixes #51

This was resolved by using `^` to escape all meta chars.
Additionally, double escaping was necessary for cmd-shim files located in `node_modules./bin/`.

Also, this commit was a major overhaul:
- Upgrade tooling
- Upgrate project to es6 (node v4)
- Fix commands as posix unix relatixe paths not working correctly
- Fix `options` argument being mutated
- Improve compliance with node's ENOENT errors
- Improve detection of node's shell option support
- Migrate project to moxystudio

BREAKING CHANGE: remove support for older nodejs versions, only node >= 4 is supported

### CODE REVIEW

**Comment by satazor** [comment]
This PR is blocked until a bug in npm is solved regarding executables in `node_modules/.bin`.

**Comment by cspotcode** [comment]
@satazor: I'm curious, what's the NPM bug?  Do you have a link to their issue tracker?

**Comment by satazor** [comment]
I can't disclose the bug because it's also a security vulnerability.

I can email you though.

**Comment by cspotcode** [comment]
Sure, I'm cspotcode@gmail.com.  Thanks.

**Comment by andrew-c-tran** [comment]
Any updates to this PR? I've traced a webpack bundling warning in my electron app back to this library attempting to require spawn-sync. This PR by removing node v0.10 support, that should correct the build warning.

**Comment by satazor** [comment]
I've updated the PR. I will merge this once it becomes green and release 6.0.0.

**Comment by satazor** [comment]
@cspotcode I've fixed the issue regarding the npm cmd-shim by double-escaping the windows shell meta chars. I've tested this exhaustively and it's working correctly!

**Pull request merged**
